name: ci
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.82.0"
          default: true

      - run: cargo test
      
      - name: run cross build for Andriod (on Linux)
        run: |
          cargo install cross
          cross build --target aarch64-linux-android
        if: matrix.os == 'ubuntu-latest'

      - name: run cross build for iOS (on macOS)
        run: |
          cargo install cross
          rustup target add aarch64-apple-ios
          cross build --target aarch64-apple-ios
        if: matrix.os == 'macos-latest'

      - name: setup zig for cargo-zigbuild (on macOS)
        uses: mlugg/setup-zig@v1
        if: matrix.os == 'macos-latest'

      - name: run cargo-zigbuild for Linux (on macOS)
        run: |
          cargo install --locked cargo-zigbuild
          rustup target add aarch64-unknown-linux-gnu
          cargo zigbuild --target aarch64-unknown-linux-gnu
        if: matrix.os == 'macos-latest'
